EnglishDictionary/urls.py
from django.urls import path , include
from EnglishDictionary import views

app_name = "EnglishDictionary"

urlpatterns = [
    path('',views.index, name="index"),
]

dictionary/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("EnglishDictionary.urls", namespace="EnglishDictionary")),
    path('words/', include("words.urls", namespace="words")),
]

users/urls.py
from django.urls import path , include
from users import views

app_name = "users"

urlpatterns = [
    path('login/',views.login, name="login"),
    path('logout/',views.logout, name="logout"),
    path('signup/',views.signup, name="signup"),
]

words/urls.py
from django.urls import path , include
from words import views

app_name = "words"

urlpatterns = [
    path('create/',views.create_word, name="create_word"),
    path('',views.search, name="search"),
]

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

words/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User" , on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class Word(models.Model):
    word = models.CharField(max_length=100 , unique=True)
    definition = models.TextField()
    synonymns = models.CharField(max_length=255)

    author = models.ForeignKey("words.Author", on_delete = models.CASCADE)


    def __str__(self):
        return self.word

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","last_name","email","username","password"]
        widgets = {
            "password" : forms.widgets.PasswordInput()
        }

words/forms.py
from django import forms
from words.models import Word

class WordForm(forms.ModelForm):
    class Meta:
        model = Word
        fields = ['word', 'definition','synonymns']

        error_message = {
            "word" : {
                "required" : "word field is required"
            },
            "definition" : {
                "required" : "definition field is required"
            },
            "word" : {
                "synonymns" : "synonymns field is required"
            },
        }

EnglishDictionary/views.py
from django.shortcuts import render
from django.http.response import HttpResponse


context = {
    "title" : "Home page"
}

def index(request):
    return render(request, 'web/index.html', context=context)

main/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render , reverse

from django.contrib.auth import authenticate , login as auth_login , logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User

from users.forms import UserForm
from main.function import generate_form_errors
from words.models import Author


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username , password=password)
            if user is not None:
                auth_login(request,user)

                return HttpResponseRedirect("/")
            
            else:
                context = {
                    "title" : "Login",
                    "error" : True,
                    "message" : "Invalid username or password"
                }
                return render(request, "users/login.html",context=context)

        else:
            context = {
                "title" : "Login",
                "error" : True,
                "message" : "Invalid username or password"
            }
            return render(request, "users/login.html",context=context)

    context={
        "title" : "Login"
    }
    return render(request, "users/login.html",context=context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("EnglishDictionary:index"))


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username = instance.username,
                password = instance.password,
                email = instance.email,
                first_name = instance.first_name,
                last_name = instance.last_name,
            )

            Author.objects.create(name=instance.first_name ,user=user)

            user = authenticate(request, username = instance.username , password = instance.password)
            auth_login(request,user)

            return HttpResponseRedirect(reverse("EnglishDictionary:index"))
        else: 
            message = generate_form_errors(form)
            
            form = UserForm()
            context = {
                "title" : "Signup",
                "error" : True,
                "message" : message,
                "form" : form ,
            }
            return render(request, "users/signup.html",context=context)

    else:
        form = UserForm()
        context = {
            "title" : "signup" ,
            "form" : form ,
    }
    return render(request , "users/signup.html" , context=context)

words/views.py
import json

from django.shortcuts import render 
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from words.forms import WordForm
from words.models import Author , Word
from main.function import generate_form_errors

@login_required(login_url="/users/login/")
def create_word(request):
    if request.method == "POST":
        form = WordForm(request.POST,request.FILES)
        if form.is_valid():
            if not Author.objects.filter(user = request.user).exists():
                author = Author.objects.create(user=request.user,name=request.user.username)
            else:
                author = request.user.author

            instance = form.save(commit=False)
            instance.author = author
            instance.save()

            response_data = {
                "title" : "Successfully submitted",
                "message" : "Successfully submitted",
                "status" : "success",
                "redirect" : "yes",
                "redirect_url" : "/"
            }

           
        else:
            error_message = generate_form_errors(form)
            response_data = {
                "title" : "form validation error",
                "message" : str(error_message),
                "status" : "error",
                "stable" : "yes"
            }

        return HttpResponse(json.dumps(response_data),content_type="application/json")
        
    else:
        form = WordForm()
        context = {
                "title": "Create word",
                "form": form,
        }
        return render(request, "words/create.html", context=context)
    

def search(request):
    query = request.GET.get('q', '').strip()
    if query:
        results = Word.objects.filter(word__istartswith=query)
        no_results = not results.exists()
        return render(request, 'web/index.html', {'results': results, 'query': query, 'no_results': no_results})
    else:
        return render(request, 'web/index.html', {'results': None, 'query': '', 'no_results': False})

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <title>Dictionary | Research your thoughts</title>
        <link
            rel="stylesheet"
            href="{% static './css/style.css'%}"
            type="text/css"
        />
        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="./images/icons/blog-logo.svg"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta property="og:image" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <script src="{% static './js/jquery-3.6.0.min.js' %}"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{% static './js/script.js' %}"></script>
    </head>
    <body> 
        {% block content %}
        {% endblock %}
    </body>
    </html>
    

templates/users/auth_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
            name="viewport"
            content="width=<device-width>, initial-scale=1.0"
        />

        <link rel="stylesheet" href="{% static './css/auth-style.css' %}" />

        <title>Signup</title>
    </head>
    <body>
        <section class="container">
            {%  block content %} {% endblock %}

        </section>
    </body>
</html>

templates/users/login.html
{% extends "users/auth_base.html" %}
    {%  load static %}
        {%  block content %}
       
            <section class="form_container">
                <div class="top">
                    <h5>Login Page</h5>
                </div>
                <div class="bottom">
                    <form action="" method="POST" >
                        {% csrf_token %}
                        <div class="input_container">
                            <label for="id_username"> Username </label>
                            <input id="id_username" name="username" type="text" />
                        </div>
                        <div class="input_container">
                            <label for="id_password"> Password </label>
                            <input id="id_password" name="password" type="password" />
                        </div>
                        <div class="submit_container">
                            {% if error %}
                                <p class="error-message">{{message}}</p>
                            {% endif %}
                            <button type="submit">Log in</button>

                            <a href="{% url 'users:signup' %}">Create Account</a>
                        </div>
                    </form>
                </div>
            </section>
        {%  endblock %}

templates/users/signup.html
{% extends "users/auth_base.html" %}
    {% load static %}
        {%  block content %}
            <section class="form_container">
                <div class="top">
                    <h5>Login Page</h5>
                </div>
                <div class="bottom">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="input_container">
                                <label for="{{field.id_for_label}}">{{field.label}}</label>
                                {{field}}
                            </div>
                        {% endfor %}
                        
                        <div class="submit_container">
                            {% if error %}
                            <p class="error-message">
                                {{message}}
                            </p>
                            {% endif %}
                            <button type="submit">Create Account</button>

                            <a href="{% url 'users:login' %}">Login</a>
                        </div>
                    </form>
                </div>
            </section>

        {%  endblock %}

templates/web/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<section id="home">
    <section class="wrapper">
        <header>
            <h1>
                <a href="./index.html">
                    <img src="{% static './images/dictionary.png' %}" alt="Logo" />
                </a>
            </h1>
            <div id="dictionary">
                <H1>
                    ENGLISH DICTIONARY
                </H1>
            </div>
            <div>
                {% if request.user.is_authenticated %}
                <a href="{% url 'words:create_word' %}" class="login my-words">Add</a>
                <a href="{% url 'users:logout'%}" class="login"> Logout </a>
                {% else %}
                <a href="{% url 'users:login'%}" class="login"> Login </a>
                {% endif %}
                <div>
        </header>
        <section class="main_container">
            <section class="spotlight">
                <h1 class="search-heading">
                    DICTIONARY SEARCH</h1>
                <section class="form">
                    <form  method="get" action="{% url 'words:search' %}">
                        <input type="text" name="q" placeholder="Search for a word" value="{{query}}" class="search-form">
                        <button type="submit" class="search-button">Search</button>
                    </form>
                    {% if no_results %}
                    <p>No results found for "{{ query }}".</p>
                    {% else %}
                </section>
               
                <section class="result">
                    <ul>
                        {% for word in results %}
                        <li>
                            <p class="search-word">Word : {{ word.word }}</p>
                        </li>
                        <li>
                            <p class="search-definition">Definition : {{ word.definition }}</p>
                        </li>
                        <li>
                            <p class="search-synonymns">Synonymns : {{ word.synonymns }}</p>
                        </li>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </section>
            </section>
        </section>
    </section>
</section>

{% endblock %}

templates/words/create.html
{% extends "base.html" %}
    {% block content %}
        {% load static %}
        <section id="home">
            <section class="wrapper">
                <header>
                    <h1>
                        <a href="./index.html">
                            <img
                                src="{% static './images/dictionary.png' %}"
                                alt="Logo"
                            />
                        </a>
                    </h1>
                    <div id="dictionary">
                        <H1>
                            ENGLISH DICTIONARY
                        </H1>
                    </div>
                    <div>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'EnglishDictionary:index' %}" class="login my-words">Home</a>
                            <a href="{% url 'users:logout'%}" class="login"> Logout </a>
                        {% else %}
                            <a href="{% url 'users:login'%}" class="login"> Login </a>
                        {% endif %}
                    <div>
                </header>    
                <section class="add_word">
                    <section class="spotword">
                        <section class="top">
                            <h1 class="word-heading">Add Word to Dictionary</h1>
                        </section>
                        <section class="bottom">
                            <form action="" method="POST" class="ajax redirect" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-field1">
                                    <label for="{{form.word.id_for_label}}" class="subheads" >
                                        {{form.word.label}} :
                                    </label>
                                    {{form.word}}
                                </div>
                                <div class="form-field2">
                                    <label class="subheads" for="{{form.definition.id_for_label}}">
                                        {{form.definition.label}} :
                                    </label>
                                    <div class="definition">
                                        <div class="editor" data-field-id="id_definition" style="display: inline-block;">
                                            {{form.definition}}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-field3">
                                    <label class="subheads" for="{{form.synonymns.id_for_label}}">
                                        {{form.synonymns.label}} :
                                    </label>
                                    <div class="editor" data-field-id="id_synonymns" style="display: inline-block;">
                                       {{form.synonymns}}
                                    </div>
                                </div>
                               
                                <div class="form-field4">
                                    <input type="submit" value="Submit" style="color: #ffff;" />
                                </div>
                            </form>
                        </section>   
                    </section>
                </section>
            </section>
        </section>
    {% endblock %}
    